version: "3"
services:
  db:
    image: cassandra
    volumes:
      - /tmp/db:/var/lib/cassandra/data

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_CREATE_TOPICS: "stock:1:1:compact,tweet:1:1:compact"
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  stockconsumer:
    image: stockconsumer
    depends_on:
      - "db"
      - "kafka"

  tweetconsumer:
    image: tweetconsumer
    depends_on:
      - "db"
      - "kafka"

  stockingest:
    image: stockingest
    volumes:
      - /tmp/stock:/stock
    depends_on:
      - "kafka"

  tweetingest:
    image: tweetingest
    volumes:
      - /tmp/tweet:/tweet
    depends_on:
      - "kafka"

  nlp:
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./nlp/__data__:/nlp

  compute:
    image: gettyimages/spark

  vis:
    image: xemuliam/zeppelin
    ports:
      - "8000:8080"
      - "8443:32774"
